spring:
  application:
    name: storage
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

minio:
  url: http://172.20.0.2:9000
  access-key: ${MINIO_ROOT_USER:minio}
  secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}
  bucket:
    name: mybucket
